source 'https://rubygems.org'

gem 'sinatra', '~> 1.3.0'
gem 'sinatra-contrib', '~> 1.3.1'
gem 'sinatra-param', '~> 0.1.3'
gem 'rake'
gem 'pg'
gem 'activesupport', '~> 4.2.0'
gem 'activemodel', '~> 4.2.0'
gem 'activerecord', '~> 4.2.0'
gem 'protected_attributes', '~> 1.0.8'
gem 'compass'
gem 'sass'
gem 'uglifier'
gem 'sprockets'
gem 'sprockets-sass'
gem 'sprockets-helpers'
gem 'unicorn'
